/*
 * This file is generated by jOOQ.
 */
package in.eduthon.user.persistence.model;


import in.eduthon.user.persistence.model.tables.Authors;
import in.eduthon.user.persistence.model.tables.Books;
import in.eduthon.user.persistence.model.tables.Databasechangeloglock;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>win_stock</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index AUTHORS_PRIMARY = Indexes0.AUTHORS_PRIMARY;
    public static final Index BOOKS_AUTHOR_FK = Indexes0.BOOKS_AUTHOR_FK;
    public static final Index BOOKS_ID = Indexes0.BOOKS_ID;
    public static final Index BOOKS_NAME = Indexes0.BOOKS_NAME;
    public static final Index BOOKS_PRIMARY = Indexes0.BOOKS_PRIMARY;
    public static final Index DATABASECHANGELOGLOCK_PRIMARY = Indexes0.DATABASECHANGELOGLOCK_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index AUTHORS_PRIMARY = Internal.createIndex("PRIMARY", Authors.AUTHORS, new OrderField[] { Authors.AUTHORS.ID }, true);
        public static Index BOOKS_AUTHOR_FK = Internal.createIndex("author_fk", Books.BOOKS, new OrderField[] { Books.BOOKS.AUTHOR }, false);
        public static Index BOOKS_ID = Internal.createIndex("id", Books.BOOKS, new OrderField[] { Books.BOOKS.ID }, true);
        public static Index BOOKS_NAME = Internal.createIndex("name", Books.BOOKS, new OrderField[] { Books.BOOKS.NAME }, true);
        public static Index BOOKS_PRIMARY = Internal.createIndex("PRIMARY", Books.BOOKS, new OrderField[] { Books.BOOKS.ID }, true);
        public static Index DATABASECHANGELOGLOCK_PRIMARY = Internal.createIndex("PRIMARY", Databasechangeloglock.DATABASECHANGELOGLOCK, new OrderField[] { Databasechangeloglock.DATABASECHANGELOGLOCK.ID }, true);
    }
}
