/*
 * This file is generated by jOOQ.
 */
package in.eduthon.user.persistence.model;


import in.eduthon.user.persistence.model.tables.Authors;
import in.eduthon.user.persistence.model.tables.Books;
import in.eduthon.user.persistence.model.tables.Databasechangeloglock;
import in.eduthon.user.persistence.model.tables.records.AuthorsRecord;
import in.eduthon.user.persistence.model.tables.records.BooksRecord;
import in.eduthon.user.persistence.model.tables.records.DatabasechangeloglockRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>win_stock</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AuthorsRecord> KEY_AUTHORS_PRIMARY = UniqueKeys0.KEY_AUTHORS_PRIMARY;
    public static final UniqueKey<BooksRecord> KEY_BOOKS_PRIMARY = UniqueKeys0.KEY_BOOKS_PRIMARY;
    public static final UniqueKey<BooksRecord> KEY_BOOKS_ID = UniqueKeys0.KEY_BOOKS_ID;
    public static final UniqueKey<BooksRecord> KEY_BOOKS_NAME = UniqueKeys0.KEY_BOOKS_NAME;
    public static final UniqueKey<DatabasechangeloglockRecord> KEY_DATABASECHANGELOGLOCK_PRIMARY = UniqueKeys0.KEY_DATABASECHANGELOGLOCK_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<BooksRecord, AuthorsRecord> AUTHOR_FK = ForeignKeys0.AUTHOR_FK;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<AuthorsRecord> KEY_AUTHORS_PRIMARY = Internal.createUniqueKey(Authors.AUTHORS, "KEY_authors_PRIMARY", Authors.AUTHORS.ID);
        public static final UniqueKey<BooksRecord> KEY_BOOKS_PRIMARY = Internal.createUniqueKey(Books.BOOKS, "KEY_books_PRIMARY", Books.BOOKS.ID);
        public static final UniqueKey<BooksRecord> KEY_BOOKS_ID = Internal.createUniqueKey(Books.BOOKS, "KEY_books_id", Books.BOOKS.ID);
        public static final UniqueKey<BooksRecord> KEY_BOOKS_NAME = Internal.createUniqueKey(Books.BOOKS, "KEY_books_name", Books.BOOKS.NAME);
        public static final UniqueKey<DatabasechangeloglockRecord> KEY_DATABASECHANGELOGLOCK_PRIMARY = Internal.createUniqueKey(Databasechangeloglock.DATABASECHANGELOGLOCK, "KEY_DATABASECHANGELOGLOCK_PRIMARY", Databasechangeloglock.DATABASECHANGELOGLOCK.ID);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<BooksRecord, AuthorsRecord> AUTHOR_FK = Internal.createForeignKey(in.eduthon.user.persistence.model.Keys.KEY_AUTHORS_PRIMARY, Books.BOOKS, "author_fk", Books.BOOKS.AUTHOR);
    }
}
