/*
 * This file is generated by jOOQ.
 */
package in.eduthon.user.persistence.model;


import in.eduthon.user.persistence.model.tables.Authors;
import in.eduthon.user.persistence.model.tables.Books;
import in.eduthon.user.persistence.model.tables.Databasechangelog;
import in.eduthon.user.persistence.model.tables.Databasechangeloglock;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in win_stock
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * A table to contain all the authors
     */
    public static final Authors AUTHORS = in.eduthon.user.persistence.model.tables.Authors.AUTHORS;

    /**
     * A table to contain all books
     */
    public static final Books BOOKS = in.eduthon.user.persistence.model.tables.Books.BOOKS;

    /**
     * The table <code>win_stock.DATABASECHANGELOG</code>.
     */
    public static final Databasechangelog DATABASECHANGELOG = in.eduthon.user.persistence.model.tables.Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>win_stock.DATABASECHANGELOGLOCK</code>.
     */
    public static final Databasechangeloglock DATABASECHANGELOGLOCK = in.eduthon.user.persistence.model.tables.Databasechangeloglock.DATABASECHANGELOGLOCK;
}
