/*
 * This file is generated by jOOQ.
 */
package in.eduthon.user.persistence.model;


import in.eduthon.user.persistence.model.tables.Authors;
import in.eduthon.user.persistence.model.tables.Books;
import in.eduthon.user.persistence.model.tables.Databasechangelog;
import in.eduthon.user.persistence.model.tables.Databasechangeloglock;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WinStock extends SchemaImpl {

    private static final long serialVersionUID = 467662091;

    /**
     * The reference instance of <code>win_stock</code>
     */
    public static final WinStock WIN_STOCK = new WinStock();

    /**
     * A table to contain all the authors
     */
    public final Authors AUTHORS = in.eduthon.user.persistence.model.tables.Authors.AUTHORS;

    /**
     * A table to contain all books
     */
    public final Books BOOKS = in.eduthon.user.persistence.model.tables.Books.BOOKS;

    /**
     * The table <code>win_stock.DATABASECHANGELOG</code>.
     */
    public final Databasechangelog DATABASECHANGELOG = in.eduthon.user.persistence.model.tables.Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>win_stock.DATABASECHANGELOGLOCK</code>.
     */
    public final Databasechangeloglock DATABASECHANGELOGLOCK = in.eduthon.user.persistence.model.tables.Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * No further instances allowed
     */
    private WinStock() {
        super("win_stock", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Authors.AUTHORS,
            Books.BOOKS,
            Databasechangelog.DATABASECHANGELOG,
            Databasechangeloglock.DATABASECHANGELOGLOCK);
    }
}
